//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedTests {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Reflection;
    using Microsoft.SpecExplorer.Runtime.Testing;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Spec Explorer", "3.5.3130.0")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GetTestSuite : VsTestClassBase {
        
        public GetTestSuite() {
            this.SetSwitch("ProceedControlTimeout", "100");
            this.SetSwitch("QuiescenceTimeout", "30000");
        }
        
        #region Event Metadata
        static System.Reflection.MethodBase initializeInfo = TestManagerHelpers.GetMethodInfo(typeof(SpecExplorer2.TFTPClientAdapter), "initialize");
        #endregion
        
        #region Test Initialization and Cleanup
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize() {
            this.InitializeTestManager();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestCleanup() {
            this.CleanupTestManager();
        }
        #endregion
        
        #region Test Starting in S0
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS0() {
            this.Manager.BeginTest("GetTestSuiteS0");
            this.Manager.Comment("reaching state \'S0\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S1\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S1\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S1\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S10
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS10() {
            this.Manager.BeginTest("GetTestSuiteS10");
            this.Manager.Comment("reaching state \'S10\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S11\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S11\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S11\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S100
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS100() {
            this.Manager.BeginTest("GetTestSuiteS100");
            this.Manager.Comment("reaching state \'S100\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S101\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S101\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S101\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S102
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS102() {
            this.Manager.BeginTest("GetTestSuiteS102");
            this.Manager.Comment("reaching state \'S102\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S103\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S103\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S103\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S104
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS104() {
            this.Manager.BeginTest("GetTestSuiteS104");
            this.Manager.Comment("reaching state \'S104\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S105\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S105\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S105\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S106
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS106() {
            this.Manager.BeginTest("GetTestSuiteS106");
            this.Manager.Comment("reaching state \'S106\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S107\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S107\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S107\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S108
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS108() {
            this.Manager.BeginTest("GetTestSuiteS108");
            this.Manager.Comment("reaching state \'S108\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S109\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S109\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S109\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S110
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS110() {
            this.Manager.BeginTest("GetTestSuiteS110");
            this.Manager.Comment("reaching state \'S110\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S111\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S111\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S111\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S112
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS112() {
            this.Manager.BeginTest("GetTestSuiteS112");
            this.Manager.Comment("reaching state \'S112\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S113\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S113\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S113\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S114
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS114() {
            this.Manager.BeginTest("GetTestSuiteS114");
            this.Manager.Comment("reaching state \'S114\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S115\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S115\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S115\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S116
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS116() {
            this.Manager.BeginTest("GetTestSuiteS116");
            this.Manager.Comment("reaching state \'S116\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S117\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S117\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S117\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S118
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS118() {
            this.Manager.BeginTest("GetTestSuiteS118");
            this.Manager.Comment("reaching state \'S118\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S119\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S119\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S119\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S12
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS12() {
            this.Manager.BeginTest("GetTestSuiteS12");
            this.Manager.Comment("reaching state \'S12\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S13\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S13\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S13\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S120
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS120() {
            this.Manager.BeginTest("GetTestSuiteS120");
            this.Manager.Comment("reaching state \'S120\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S121\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S121\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S121\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S122
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS122() {
            this.Manager.BeginTest("GetTestSuiteS122");
            this.Manager.Comment("reaching state \'S122\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S123\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S123\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S123\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S124
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS124() {
            this.Manager.BeginTest("GetTestSuiteS124");
            this.Manager.Comment("reaching state \'S124\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S125\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S125\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S125\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S126
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS126() {
            this.Manager.BeginTest("GetTestSuiteS126");
            this.Manager.Comment("reaching state \'S126\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S127\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S127\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S127\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S14
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS14() {
            this.Manager.BeginTest("GetTestSuiteS14");
            this.Manager.Comment("reaching state \'S14\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S15\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S15\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S15\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S16
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS16() {
            this.Manager.BeginTest("GetTestSuiteS16");
            this.Manager.Comment("reaching state \'S16\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S17\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S17\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S17\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S18
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS18() {
            this.Manager.BeginTest("GetTestSuiteS18");
            this.Manager.Comment("reaching state \'S18\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S19\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S19\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S19\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S2
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS2() {
            this.Manager.BeginTest("GetTestSuiteS2");
            this.Manager.Comment("reaching state \'S2\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S3\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S3\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S3\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S20
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS20() {
            this.Manager.BeginTest("GetTestSuiteS20");
            this.Manager.Comment("reaching state \'S20\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S21\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S21\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S21\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S22
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS22() {
            this.Manager.BeginTest("GetTestSuiteS22");
            this.Manager.Comment("reaching state \'S22\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S23\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S23\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S23\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S24
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS24() {
            this.Manager.BeginTest("GetTestSuiteS24");
            this.Manager.Comment("reaching state \'S24\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S25\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S25\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S25\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S26
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS26() {
            this.Manager.BeginTest("GetTestSuiteS26");
            this.Manager.Comment("reaching state \'S26\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S27\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S27\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S27\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S28
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS28() {
            this.Manager.BeginTest("GetTestSuiteS28");
            this.Manager.Comment("reaching state \'S28\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S29\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S29\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S29\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S30
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS30() {
            this.Manager.BeginTest("GetTestSuiteS30");
            this.Manager.Comment("reaching state \'S30\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S31\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S31\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S31\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S32
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS32() {
            this.Manager.BeginTest("GetTestSuiteS32");
            this.Manager.Comment("reaching state \'S32\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S33\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S33\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S33\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S34
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS34() {
            this.Manager.BeginTest("GetTestSuiteS34");
            this.Manager.Comment("reaching state \'S34\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S35\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S35\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S35\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S36
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS36() {
            this.Manager.BeginTest("GetTestSuiteS36");
            this.Manager.Comment("reaching state \'S36\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S37\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S37\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S37\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S38
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS38() {
            this.Manager.BeginTest("GetTestSuiteS38");
            this.Manager.Comment("reaching state \'S38\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S39\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S39\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S39\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S4
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS4() {
            this.Manager.BeginTest("GetTestSuiteS4");
            this.Manager.Comment("reaching state \'S4\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S5\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S5\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S5\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S40
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS40() {
            this.Manager.BeginTest("GetTestSuiteS40");
            this.Manager.Comment("reaching state \'S40\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S41\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S41\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S41\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S42
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS42() {
            this.Manager.BeginTest("GetTestSuiteS42");
            this.Manager.Comment("reaching state \'S42\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S43\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S43\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S43\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S44
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS44() {
            this.Manager.BeginTest("GetTestSuiteS44");
            this.Manager.Comment("reaching state \'S44\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S45\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S45\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S45\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S46
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS46() {
            this.Manager.BeginTest("GetTestSuiteS46");
            this.Manager.Comment("reaching state \'S46\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S47\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S47\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S47\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S48
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS48() {
            this.Manager.BeginTest("GetTestSuiteS48");
            this.Manager.Comment("reaching state \'S48\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S49\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S49\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S49\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S50
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS50() {
            this.Manager.BeginTest("GetTestSuiteS50");
            this.Manager.Comment("reaching state \'S50\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S51\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S51\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S51\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S52
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS52() {
            this.Manager.BeginTest("GetTestSuiteS52");
            this.Manager.Comment("reaching state \'S52\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S53\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S53\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S53\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S54
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS54() {
            this.Manager.BeginTest("GetTestSuiteS54");
            this.Manager.Comment("reaching state \'S54\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S55\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S55\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S55\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S56
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS56() {
            this.Manager.BeginTest("GetTestSuiteS56");
            this.Manager.Comment("reaching state \'S56\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S57\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S57\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S57\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S58
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS58() {
            this.Manager.BeginTest("GetTestSuiteS58");
            this.Manager.Comment("reaching state \'S58\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S59\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S59\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S59\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S6
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS6() {
            this.Manager.BeginTest("GetTestSuiteS6");
            this.Manager.Comment("reaching state \'S6\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S7\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S7\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S7\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S60
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS60() {
            this.Manager.BeginTest("GetTestSuiteS60");
            this.Manager.Comment("reaching state \'S60\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S61\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S61\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S61\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S62
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS62() {
            this.Manager.BeginTest("GetTestSuiteS62");
            this.Manager.Comment("reaching state \'S62\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S63\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S63\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S63\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S64
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS64() {
            this.Manager.BeginTest("GetTestSuiteS64");
            this.Manager.Comment("reaching state \'S64\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S65\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S65\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S65\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S66
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS66() {
            this.Manager.BeginTest("GetTestSuiteS66");
            this.Manager.Comment("reaching state \'S66\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S67\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S67\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S67\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S68
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS68() {
            this.Manager.BeginTest("GetTestSuiteS68");
            this.Manager.Comment("reaching state \'S68\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S69\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S69\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S69\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S70
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS70() {
            this.Manager.BeginTest("GetTestSuiteS70");
            this.Manager.Comment("reaching state \'S70\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S71\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S71\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S71\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S72
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS72() {
            this.Manager.BeginTest("GetTestSuiteS72");
            this.Manager.Comment("reaching state \'S72\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S73\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S73\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S73\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S74
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS74() {
            this.Manager.BeginTest("GetTestSuiteS74");
            this.Manager.Comment("reaching state \'S74\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S75\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S75\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S75\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S76
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS76() {
            this.Manager.BeginTest("GetTestSuiteS76");
            this.Manager.Comment("reaching state \'S76\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S77\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S77\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S77\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S78
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS78() {
            this.Manager.BeginTest("GetTestSuiteS78");
            this.Manager.Comment("reaching state \'S78\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S79\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S79\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S79\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S8
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS8() {
            this.Manager.BeginTest("GetTestSuiteS8");
            this.Manager.Comment("reaching state \'S8\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S9\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S9\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S9\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S80
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS80() {
            this.Manager.BeginTest("GetTestSuiteS80");
            this.Manager.Comment("reaching state \'S80\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S81\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S81\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S81\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S82
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS82() {
            this.Manager.BeginTest("GetTestSuiteS82");
            this.Manager.Comment("reaching state \'S82\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S83\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S83\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S83\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S84
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS84() {
            this.Manager.BeginTest("GetTestSuiteS84");
            this.Manager.Comment("reaching state \'S84\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S85\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S85\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S85\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S86
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS86() {
            this.Manager.BeginTest("GetTestSuiteS86");
            this.Manager.Comment("reaching state \'S86\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S87\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S87\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S87\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S88
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS88() {
            this.Manager.BeginTest("GetTestSuiteS88");
            this.Manager.Comment("reaching state \'S88\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S89\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S89\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S89\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S90
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS90() {
            this.Manager.BeginTest("GetTestSuiteS90");
            this.Manager.Comment("reaching state \'S90\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S91\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S91\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S91\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S92
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS92() {
            this.Manager.BeginTest("GetTestSuiteS92");
            this.Manager.Comment("reaching state \'S92\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S93\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S93\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S93\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S94
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS94() {
            this.Manager.BeginTest("GetTestSuiteS94");
            this.Manager.Comment("reaching state \'S94\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S95\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S95\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S95\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S96
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS96() {
            this.Manager.BeginTest("GetTestSuiteS96");
            this.Manager.Comment("reaching state \'S96\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S97\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S97\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S97\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S98
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void GetTestSuiteS98() {
            this.Manager.BeginTest("GetTestSuiteS98");
            this.Manager.Comment("reaching state \'S98\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S99\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S99\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S99\'.");
            this.Manager.EndTest();
        }
        #endregion
    }
}
