//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedTests {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Reflection;
    using Microsoft.SpecExplorer.Runtime.Testing;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Spec Explorer", "3.5.3130.0")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PutTestSuite : VsTestClassBase {
        
        public PutTestSuite() {
            this.SetSwitch("ProceedControlTimeout", "100");
            this.SetSwitch("QuiescenceTimeout", "30000");
        }
        
        #region Event Metadata
        static System.Reflection.MethodBase initializeInfo = TestManagerHelpers.GetMethodInfo(typeof(SpecExplorer2.TFTPClientAdapter), "initialize");
        #endregion
        
        #region Test Initialization and Cleanup
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize() {
            this.InitializeTestManager();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestCleanup() {
            this.CleanupTestManager();
        }
        #endregion
        
        #region Test Starting in S0
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS0() {
            this.Manager.BeginTest("PutTestSuiteS0");
            this.Manager.Comment("reaching state \'S0\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S1\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S1\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S1\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S10
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS10() {
            this.Manager.BeginTest("PutTestSuiteS10");
            this.Manager.Comment("reaching state \'S10\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S11\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S11\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S11\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S100
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS100() {
            this.Manager.BeginTest("PutTestSuiteS100");
            this.Manager.Comment("reaching state \'S100\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S101\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S101\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S101\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S102
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS102() {
            this.Manager.BeginTest("PutTestSuiteS102");
            this.Manager.Comment("reaching state \'S102\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S103\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S103\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S103\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S104
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS104() {
            this.Manager.BeginTest("PutTestSuiteS104");
            this.Manager.Comment("reaching state \'S104\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S105\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S105\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S105\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S106
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS106() {
            this.Manager.BeginTest("PutTestSuiteS106");
            this.Manager.Comment("reaching state \'S106\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S107\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S107\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S107\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S108
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS108() {
            this.Manager.BeginTest("PutTestSuiteS108");
            this.Manager.Comment("reaching state \'S108\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S109\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S109\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S109\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S110
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS110() {
            this.Manager.BeginTest("PutTestSuiteS110");
            this.Manager.Comment("reaching state \'S110\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S111\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S111\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S111\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S112
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS112() {
            this.Manager.BeginTest("PutTestSuiteS112");
            this.Manager.Comment("reaching state \'S112\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S113\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S113\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S113\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S114
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS114() {
            this.Manager.BeginTest("PutTestSuiteS114");
            this.Manager.Comment("reaching state \'S114\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S115\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S115\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S115\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S116
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS116() {
            this.Manager.BeginTest("PutTestSuiteS116");
            this.Manager.Comment("reaching state \'S116\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S117\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S117\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S117\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S118
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS118() {
            this.Manager.BeginTest("PutTestSuiteS118");
            this.Manager.Comment("reaching state \'S118\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S119\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S119\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S119\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S12
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS12() {
            this.Manager.BeginTest("PutTestSuiteS12");
            this.Manager.Comment("reaching state \'S12\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S13\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S13\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S13\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S120
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS120() {
            this.Manager.BeginTest("PutTestSuiteS120");
            this.Manager.Comment("reaching state \'S120\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S121\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S121\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S121\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S122
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS122() {
            this.Manager.BeginTest("PutTestSuiteS122");
            this.Manager.Comment("reaching state \'S122\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S123\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S123\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S123\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S124
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS124() {
            this.Manager.BeginTest("PutTestSuiteS124");
            this.Manager.Comment("reaching state \'S124\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S125\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S125\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S125\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S126
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS126() {
            this.Manager.BeginTest("PutTestSuiteS126");
            this.Manager.Comment("reaching state \'S126\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S127\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S127\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S127\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S14
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS14() {
            this.Manager.BeginTest("PutTestSuiteS14");
            this.Manager.Comment("reaching state \'S14\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S15\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S15\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S15\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S16
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS16() {
            this.Manager.BeginTest("PutTestSuiteS16");
            this.Manager.Comment("reaching state \'S16\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S17\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S17\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S17\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S18
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS18() {
            this.Manager.BeginTest("PutTestSuiteS18");
            this.Manager.Comment("reaching state \'S18\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S19\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S19\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S19\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S2
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS2() {
            this.Manager.BeginTest("PutTestSuiteS2");
            this.Manager.Comment("reaching state \'S2\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S3\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S3\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S3\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S20
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS20() {
            this.Manager.BeginTest("PutTestSuiteS20");
            this.Manager.Comment("reaching state \'S20\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S21\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S21\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S21\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S22
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS22() {
            this.Manager.BeginTest("PutTestSuiteS22");
            this.Manager.Comment("reaching state \'S22\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S23\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S23\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S23\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S24
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS24() {
            this.Manager.BeginTest("PutTestSuiteS24");
            this.Manager.Comment("reaching state \'S24\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S25\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S25\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S25\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S26
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS26() {
            this.Manager.BeginTest("PutTestSuiteS26");
            this.Manager.Comment("reaching state \'S26\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S27\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S27\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S27\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S28
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS28() {
            this.Manager.BeginTest("PutTestSuiteS28");
            this.Manager.Comment("reaching state \'S28\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S29\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S29\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S29\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S30
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS30() {
            this.Manager.BeginTest("PutTestSuiteS30");
            this.Manager.Comment("reaching state \'S30\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S31\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S31\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S31\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S32
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS32() {
            this.Manager.BeginTest("PutTestSuiteS32");
            this.Manager.Comment("reaching state \'S32\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S33\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S33\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S33\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S34
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS34() {
            this.Manager.BeginTest("PutTestSuiteS34");
            this.Manager.Comment("reaching state \'S34\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S35\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S35\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S35\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S36
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS36() {
            this.Manager.BeginTest("PutTestSuiteS36");
            this.Manager.Comment("reaching state \'S36\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S37\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S37\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S37\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S38
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS38() {
            this.Manager.BeginTest("PutTestSuiteS38");
            this.Manager.Comment("reaching state \'S38\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S39\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S39\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S39\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S4
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS4() {
            this.Manager.BeginTest("PutTestSuiteS4");
            this.Manager.Comment("reaching state \'S4\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S5\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S5\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S5\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S40
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS40() {
            this.Manager.BeginTest("PutTestSuiteS40");
            this.Manager.Comment("reaching state \'S40\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S41\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S41\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S41\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S42
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS42() {
            this.Manager.BeginTest("PutTestSuiteS42");
            this.Manager.Comment("reaching state \'S42\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S43\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S43\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S43\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S44
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS44() {
            this.Manager.BeginTest("PutTestSuiteS44");
            this.Manager.Comment("reaching state \'S44\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S45\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S45\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S45\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S46
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS46() {
            this.Manager.BeginTest("PutTestSuiteS46");
            this.Manager.Comment("reaching state \'S46\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S47\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S47\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S47\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S48
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS48() {
            this.Manager.BeginTest("PutTestSuiteS48");
            this.Manager.Comment("reaching state \'S48\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S49\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S49\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S49\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S50
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS50() {
            this.Manager.BeginTest("PutTestSuiteS50");
            this.Manager.Comment("reaching state \'S50\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S51\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S51\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S51\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S52
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS52() {
            this.Manager.BeginTest("PutTestSuiteS52");
            this.Manager.Comment("reaching state \'S52\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S53\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S53\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S53\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S54
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS54() {
            this.Manager.BeginTest("PutTestSuiteS54");
            this.Manager.Comment("reaching state \'S54\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S55\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S55\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S55\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S56
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS56() {
            this.Manager.BeginTest("PutTestSuiteS56");
            this.Manager.Comment("reaching state \'S56\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S57\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S57\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S57\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S58
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS58() {
            this.Manager.BeginTest("PutTestSuiteS58");
            this.Manager.Comment("reaching state \'S58\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S59\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S59\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S59\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S6
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS6() {
            this.Manager.BeginTest("PutTestSuiteS6");
            this.Manager.Comment("reaching state \'S6\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S7\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S7\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S7\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S60
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS60() {
            this.Manager.BeginTest("PutTestSuiteS60");
            this.Manager.Comment("reaching state \'S60\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S61\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S61\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S61\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S62
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS62() {
            this.Manager.BeginTest("PutTestSuiteS62");
            this.Manager.Comment("reaching state \'S62\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S63\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S63\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S63\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S64
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS64() {
            this.Manager.BeginTest("PutTestSuiteS64");
            this.Manager.Comment("reaching state \'S64\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S65\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S65\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S65\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S66
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS66() {
            this.Manager.BeginTest("PutTestSuiteS66");
            this.Manager.Comment("reaching state \'S66\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S67\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S67\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S67\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S68
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS68() {
            this.Manager.BeginTest("PutTestSuiteS68");
            this.Manager.Comment("reaching state \'S68\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S69\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S69\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S69\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S70
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS70() {
            this.Manager.BeginTest("PutTestSuiteS70");
            this.Manager.Comment("reaching state \'S70\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S71\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S71\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S71\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S72
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS72() {
            this.Manager.BeginTest("PutTestSuiteS72");
            this.Manager.Comment("reaching state \'S72\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S73\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S73\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S73\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S74
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS74() {
            this.Manager.BeginTest("PutTestSuiteS74");
            this.Manager.Comment("reaching state \'S74\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S75\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S75\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S75\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S76
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS76() {
            this.Manager.BeginTest("PutTestSuiteS76");
            this.Manager.Comment("reaching state \'S76\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S77\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S77\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S77\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S78
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS78() {
            this.Manager.BeginTest("PutTestSuiteS78");
            this.Manager.Comment("reaching state \'S78\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S79\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S79\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S79\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S8
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS8() {
            this.Manager.BeginTest("PutTestSuiteS8");
            this.Manager.Comment("reaching state \'S8\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S9\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S9\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S9\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S80
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS80() {
            this.Manager.BeginTest("PutTestSuiteS80");
            this.Manager.Comment("reaching state \'S80\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S81\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S81\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S81\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S82
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS82() {
            this.Manager.BeginTest("PutTestSuiteS82");
            this.Manager.Comment("reaching state \'S82\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S83\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S83\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S83\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S84
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS84() {
            this.Manager.BeginTest("PutTestSuiteS84");
            this.Manager.Comment("reaching state \'S84\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S85\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S85\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S85\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S86
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS86() {
            this.Manager.BeginTest("PutTestSuiteS86");
            this.Manager.Comment("reaching state \'S86\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S87\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S87\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S87\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S88
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS88() {
            this.Manager.BeginTest("PutTestSuiteS88");
            this.Manager.Comment("reaching state \'S88\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S89\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S89\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S89\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S90
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS90() {
            this.Manager.BeginTest("PutTestSuiteS90");
            this.Manager.Comment("reaching state \'S90\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S91\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S91\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S91\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S92
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS92() {
            this.Manager.BeginTest("PutTestSuiteS92");
            this.Manager.Comment("reaching state \'S92\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S93\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S93\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S93\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S94
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS94() {
            this.Manager.BeginTest("PutTestSuiteS94");
            this.Manager.Comment("reaching state \'S94\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S95\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S95\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S95\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S96
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS96() {
            this.Manager.BeginTest("PutTestSuiteS96");
            this.Manager.Comment("reaching state \'S96\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S97\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S97\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S97\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S98
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS98() {
            this.Manager.BeginTest("PutTestSuiteS98");
            this.Manager.Comment("reaching state \'S98\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.AddReturn(initializeInfo, null);
            this.Manager.Comment("reaching state \'S99\'");
            this.Manager.Assert(false, "exploration of test code generation hit a state bound at state \'S99\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S99\'.");
            this.Manager.EndTest();
        }
        #endregion
    }
}
