//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedTests {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Reflection;
    using Microsoft.SpecExplorer.Runtime.Testing;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Spec Explorer", "3.5.3130.0")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PutTestSuite : VsTestClassBase {
        
        public PutTestSuite() {
            this.SetSwitch("ProceedControlTimeout", "100");
            this.SetSwitch("QuiescenceTimeout", "30000");
        }
        
        #region Test Initialization and Cleanup
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize() {
            this.InitializeTestManager();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestCleanup() {
            this.CleanupTestManager();
        }
        #endregion
        
        #region Test Starting in S0
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS0() {
            this.Manager.BeginTest("PutTestSuiteS0");
            this.Manager.Comment("reaching state \'S0\'");
            this.Manager.Comment("executing step \'call checker(0)\'");
            SpecExplorer2.TFTPClientAdapter.checker(0);
            this.Manager.Comment("reaching state \'S1\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S4\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.Comment("reaching state \'S6\'");
            this.Manager.Comment("checking step \'return initialize\'");
            this.Manager.Comment("reaching state \'S8\'");
            this.Manager.Comment("executing step \'call checker(0)\'");
            SpecExplorer2.TFTPClientAdapter.checker(0);
            this.Manager.Comment("reaching state \'S10\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S12\'");
            this.Manager.Comment("executing step \'call sendWriteRequest()\'");
            SpecExplorer2.TFTPClientAdapter.sendWriteRequest();
            this.Manager.Comment("reaching state \'S14\'");
            this.Manager.Comment("checking step \'return sendWriteRequest\'");
            this.Manager.Comment("reaching state \'S16\'");
            this.Manager.Comment("executing step \'call checker(6)\'");
            SpecExplorer2.TFTPClientAdapter.checker(6);
            this.Manager.Comment("reaching state \'S18\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S20\'");
            this.Manager.Comment("executing step \'call receiveACK()\'");
            SpecExplorer2.TFTPClientAdapter.receiveACK();
            this.Manager.Comment("reaching state \'S22\'");
            this.Manager.Comment("checking step \'return receiveACK\'");
            this.Manager.Comment("reaching state \'S24\'");
            this.Manager.Comment("executing step \'call checker(7)\'");
            SpecExplorer2.TFTPClientAdapter.checker(7);
            this.Manager.Comment("reaching state \'S26\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S28\'");
            this.Manager.Comment("executing step \'call sendDataBlock()\'");
            SpecExplorer2.TFTPClientAdapter.sendDataBlock();
            this.Manager.Comment("reaching state \'S30\'");
            this.Manager.Comment("checking step \'return sendDataBlock\'");
            this.Manager.Comment("reaching state \'S32\'");
            this.Manager.Comment("executing step \'call checker(8)\'");
            SpecExplorer2.TFTPClientAdapter.checker(8);
            this.Manager.Comment("reaching state \'S34\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S36\'");
            this.Manager.Comment("executing step \'call canPutExit(521)\'");
            SpecExplorer2.TFTPClientAdapter.canPutExit(521);
            this.Manager.Comment("reaching state \'S38\'");
            this.Manager.Comment("checking step \'return canPutExit\'");
            this.Manager.Comment("reaching state \'S40\'");
            this.Manager.Comment("executing step \'call checker(8)\'");
            SpecExplorer2.TFTPClientAdapter.checker(8);
            this.Manager.Comment("reaching state \'S42\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S44\'");
            this.Manager.Comment("executing step \'call receiveACK()\'");
            SpecExplorer2.TFTPClientAdapter.receiveACK();
            this.Manager.Comment("reaching state \'S46\'");
            this.Manager.Comment("checking step \'return receiveACK\'");
            this.Manager.Comment("reaching state \'S47\'");
            this.Manager.Comment("executing step \'call checker(7)\'");
            SpecExplorer2.TFTPClientAdapter.checker(7);
            this.Manager.Comment("reaching state \'S48\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S49\'");
            this.Manager.Comment("executing step \'call sendDataBlock()\'");
            SpecExplorer2.TFTPClientAdapter.sendDataBlock();
            this.Manager.Comment("reaching state \'S50\'");
            this.Manager.Comment("checking step \'return sendDataBlock\'");
            this.Manager.Comment("reaching state \'S51\'");
            this.Manager.Comment("executing step \'call checker(8)\'");
            SpecExplorer2.TFTPClientAdapter.checker(8);
            this.Manager.Comment("reaching state \'S52\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S53\'");
            this.Manager.Comment("executing step \'call canPutExit(521)\'");
            SpecExplorer2.TFTPClientAdapter.canPutExit(521);
            this.Manager.Comment("reaching state \'S54\'");
            this.Manager.Comment("checking step \'return canPutExit\'");
            this.Manager.Comment("reaching state \'S55\'");
            this.Manager.Assert(false, "exploration of test code generation hit a path depth bound at state \'S55\'.");
            this.Manager.Assert(false, "reached non-accepting end state \'S55\'.");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S2
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void PutTestSuiteS2() {
            this.Manager.BeginTest("PutTestSuiteS2");
            this.Manager.Comment("reaching state \'S2\'");
            this.Manager.Comment("executing step \'call checker(0)\'");
            SpecExplorer2.TFTPClientAdapter.checker(0);
            this.Manager.Comment("reaching state \'S3\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S5\'");
            this.Manager.Comment("executing step \'call initialize()\'");
            SpecExplorer2.TFTPClientAdapter.initialize();
            this.Manager.Comment("reaching state \'S7\'");
            this.Manager.Comment("checking step \'return initialize\'");
            this.Manager.Comment("reaching state \'S9\'");
            this.Manager.Comment("executing step \'call checker(0)\'");
            SpecExplorer2.TFTPClientAdapter.checker(0);
            this.Manager.Comment("reaching state \'S11\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S13\'");
            this.Manager.Comment("executing step \'call sendWriteRequest()\'");
            SpecExplorer2.TFTPClientAdapter.sendWriteRequest();
            this.Manager.Comment("reaching state \'S15\'");
            this.Manager.Comment("checking step \'return sendWriteRequest\'");
            this.Manager.Comment("reaching state \'S17\'");
            this.Manager.Comment("executing step \'call checker(6)\'");
            SpecExplorer2.TFTPClientAdapter.checker(6);
            this.Manager.Comment("reaching state \'S19\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S21\'");
            this.Manager.Comment("executing step \'call receiveACK()\'");
            SpecExplorer2.TFTPClientAdapter.receiveACK();
            this.Manager.Comment("reaching state \'S23\'");
            this.Manager.Comment("checking step \'return receiveACK\'");
            this.Manager.Comment("reaching state \'S25\'");
            this.Manager.Comment("executing step \'call checker(7)\'");
            SpecExplorer2.TFTPClientAdapter.checker(7);
            this.Manager.Comment("reaching state \'S27\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S29\'");
            this.Manager.Comment("executing step \'call sendDataBlock()\'");
            SpecExplorer2.TFTPClientAdapter.sendDataBlock();
            this.Manager.Comment("reaching state \'S31\'");
            this.Manager.Comment("checking step \'return sendDataBlock\'");
            this.Manager.Comment("reaching state \'S33\'");
            this.Manager.Comment("executing step \'call checker(8)\'");
            SpecExplorer2.TFTPClientAdapter.checker(8);
            this.Manager.Comment("reaching state \'S35\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S37\'");
            this.Manager.Comment("executing step \'call canPutExit(511)\'");
            SpecExplorer2.TFTPClientAdapter.canPutExit(511);
            this.Manager.Comment("reaching state \'S39\'");
            this.Manager.Comment("checking step \'return canPutExit\'");
            this.Manager.Comment("reaching state \'S41\'");
            this.Manager.Comment("executing step \'call checker(1)\'");
            SpecExplorer2.TFTPClientAdapter.checker(1);
            this.Manager.Comment("reaching state \'S43\'");
            this.Manager.Comment("checking step \'return checker\'");
            this.Manager.Comment("reaching state \'S45\'");
            this.Manager.EndTest();
        }
        #endregion
    }
}
