all: MapEditor MapViewer

MapEditor: 
	javac Location.java Path.java Graph.java XmlDataSource.java Scene.java MapScene.java ZoomPane.java EditorMenu.java MapEditor.java

MapViewer: 
	javac Location.java Path.java Graph.java XmlDataSource.java Scene.java MapScene.java ZoomPane.java ViewerMenu.java MapViewer.java

clean:
	rm -f *.java~ *.class
