DROP TABLE CourseEvaluations CASCADE CONSTRAINTS;

DROP TABLE Courses CASCADE CONSTRAINTS;

DROP TABLE CourseStudents CASCADE CONSTRAINTS;

DROP TABLE Departments CASCADE CONSTRAINTS;

DROP TABLE EvaluationGrades CASCADE CONSTRAINTS;

DROP TABLE Faculties CASCADE CONSTRAINTS;

DROP TABLE Students CASCADE CONSTRAINTS;